## ----------------------------------------------------------------------------
## nexus | NEXT100.config.mac
##
## Configuration macro to simulate 0nubb decays in the
## active volume in the NEXT-100 detector.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

##### VERBOSITY #####
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/process/em/verbose 0

##### GEOMETRY #####
/Geometry/Next100/elfield false
/Geometry/Next100/max_step_size 1. mm
/Geometry/Next100/pressure 4.3 bar

##### GENERATOR #####
/Generator/Decay0Interface/region ACTIVE
/Generator/Decay0Interface/Xe136DecayMode 1
/Generator/Decay0Interface/Ba136FinalState 0

##### ACTIONS #####
/Actions/DefaultEventAction/min_energy 0.6 MeV
/Actions/DefaultEventAction/max_energy 2.55 MeV

##### PHYSICS #####
## No full simulation
/PhysicsList/Nexus/clustering          false
/PhysicsList/Nexus/drift               false
/PhysicsList/Nexus/electroluminescence false

##### PERSISTENCY #####
/nexus/persistency/output_file NEXUS_OUTPUT
## eventType options: bb0nu, bb2nu, background
/nexus/persistency/event_type background

/nexus/random_seed 10
/nexus/persistency/start_id 10